### ISSUE TITLE
    ../../logger.py导入出现问题

### ISSUE THREAD

**Issue by KristinSun** [atomicarchitects/equiformer#9]
Traceback (most recent call last):
  File "main_oc20.py", line 29, in <module>
    import oc20.trainer
  File "/home/a113/FY/Code/equiformer-master/oc20/trainer/__init__.py", line 17, in <module>
    from .energy_trainer_v2 import EnergyTrainerV2
  File "/home/a113/FY/Code/equiformer-master/oc20/trainer/energy_trainer_v2.py", line 26, in <module>
    from .base_trainer_v2 import BaseTrainerV2, interpolate_init_relaxed_pos
  File "/home/a113/FY/Code/equiformer-master/oc20/trainer/base_trainer_v2.py", line 55, in <module>
    from .logger import FileLogger
  File "/home/a113/FY/Code/equiformer-master/oc20/trainer/logger.py", line 1
    ../../logger.py
    ^
SyntaxError: invalid syntax
在导入的时候为什么会出现这个错误

**Comment by yilunliao** [comment]
Hi @KristinSun .

I have not encountered this issue. 
Can you try running on other machines/clsuters to see if that still happens?

**Comment by zhoufy20** [comment]
When we git clone the package, the `logger.py` and `engine.py` occur some errors which cannot be opened locally.

**Comment by yilunliao** [comment]
@zhoufy20 
Maybe clone again or try on other machines/clusters?
It would be good if you share error message. 

I think others can reproduce the numbers in the paper, so there should be no issues generally.

**Comment by zhoufy20** [comment]
@yilunliao ,Thanks! It is ok now, maybe the `vpn` problem.  

I would likle to inquire about how to utilize Equiformer_v2 with my dataset, which includes numerous DFT calculations, such as CONTCAR and OUTCAR files. This dataset contains information on atom positions, adjacency matrices, average atom energies, and forces acting on each atom. Is there any entry points for dgl type datset?

Your response and assistance in this would be greatly appreciated.

**Comment by yilunliao** [comment]
Hi @zhoufy20 

Can you post this question to EquiformerV2 repo instead?
